import Head from 'next/head'
import Image from 'next/image'
import Header from '../../layout/header'
import Footer from '../../layout/footer'
import Button from 'react-bootstrap/Button';

export default function Contact() {  
    return (
        <div>
        <Head>
          <title>Herbert web developer - Freelancer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className="main">
            <h1>Curriculum</h1>
        </main>
        <Footer />
        </div>
    )

}