import Head from 'next/head'
import Image from 'next/image'
import Header from '../../layout/header'
import Footer from '../../layout/footer'
import Button from 'react-bootstrap/Button';
import React from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEnvelope, faPhone } from '@fortawesome/free-solid-svg-icons'
import { faGithub, faInstagram } from '@fortawesome/free-brands-svg-icons'

export default function Contact() {
  


    return (
        <div>
        <Head>
          <title>Herbert web developer - Freelancer - Curriculum</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <div className="container mt-5 px-5">
        <div className='row pagina-contato' >
            <div className='col-12 px-5'>
            <h2 className="mb-3 titulo"><FontAwesomeIcon icon={faPhone} /> Fale Comigo</h2>
            </div>
            <div className='col-6 col-md-3 list-contato'>                
                <figure className='icon-contato'>
                <FontAwesomeIcon icon={faEnvelope} />
                </figure>
                <h5>Email</h5>
                herbert.webdesigner@gmail.com
            </div>
            <div className='col-6 col-md-3 list-contato'>                
                <figure className='icon-contato'>
                <FontAwesomeIcon icon={faPhone} />
                </figure>
                <h5>Telefone</h5>
                +353 83 381 8131
            </div>
            <div className='col-6 col-md-3 list-contato'>                
                <figure className='icon-contato'>
                <FontAwesomeIcon icon={faGithub} />
                </figure>
                <h5>Github</h5>
                herbertamaro2
            </div>
            <div className='col-6 col-md-3 list-contato'>                
                <figure className='icon-contato'>
                <FontAwesomeIcon icon={faInstagram} />
                </figure>
                <h5>Instagram</h5>
                herbert.webdesigner@gmail.com
            </div>        
        </div>
        <Footer />
        </div>
        </div>
        )
}