

import Head from 'next/head'
import Header from '../../layout/header'
import Footer from '../../layout/footer'
import Button from 'react-bootstrap/Button';
export default function Curriculum() {  
    return (
        <div>
        <Head>
          <title>Herbert web developer - Freelancer - Curriculum</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className="main">
        <div className="content-cv">
        <div id="hd">
			<div className="yui-gc">
				<div className="yui-u first">
					<h1>Herbert Amaro Santana</h1>
					<h2>Front End Developer</h2>
				</div>

				<div className="yui-u">
					<div className="contact-info">
						<h3><a>contact@herbertamaro.me</a></h3>
						<h3>(+55) 11 95898-8444</h3>
					</div>
				</div>
			</div>
		</div>

		<div id="bd">
			<div id="yui-main">
				<div className="yui-b">

					<div className="yui-gf">
						<div className="yui-u first">
							<h2>Profile</h2>
						</div>
						<div className="yui-u">
							<p className="enlarge">
								Progressively evolve cross-platform ideas before impactful infomediaries. Energistically visualize tactical initiatives before cross-media catalysts for change. 
							</p>
						</div>
					</div>

					<div className="yui-gf">
						<div className="yui-u first">
							<h2>Skills</h2>
						</div>
						<div className="yui-u">

								<div className="talent">
									<h2>Web Design</h2>
									<p>Assertively exploit wireless initiatives rather than synergistic core competencies.	</p>
								</div>

								<div className="talent">
									<h2>Interface Design</h2>
									<p>Credibly streamline mission-critical value with multifunctional functionalities.	 </p>
								</div>

								<div className="talent">
									<h2>Project Direction</h2>
									<p>Proven ability to lead and manage a wide variety of design and development projects in team and independent situations.</p>
								</div>
						</div>
					</div>

					<div className="yui-gf">
						<div className="yui-u first">
							<h2>Technical</h2>
						</div>
						<div className="yui-u">
							<ul className="talent">
								<li>XHTML</li>
								<li>CSS</li>
								<li className="last">Javascript</li>
							</ul>

							<ul className="talent">
								<li>Jquery</li>
								<li>PHP</li>
								<li className="last">CVS / Subversion</li>
							</ul>

							<ul className="talent">
								<li>OS X</li>
								<li>Windows XP/Vista</li>
								<li className="last">Linux</li>
							</ul>
						</div>
					</div>

					<div className="yui-gf">
	
						<div className="yui-u first">
							<h2>Experience</h2>
						</div>

						<div className="yui-u">

							<div className="job">
								<h2>Vaivo</h2>
								<h3>Frontend Developer</h3>
								<h4>2020</h4>
								<p>Responsible for apply received layout from Adobe XD to be applied Laravel and Vuejs
Maintenance of the trade platform and add features</p>
							</div>

							<div className="job">
								<h2>WebFamily Agência Digital</h2>
								<h3>Frontend Developer</h3>
								<h4>2015-2020</h4>
								<p>esponsible to create websites from zero (design to programming).
Responsible for creating and maintaining the credit analysis platform (main project of the agency)
Wordpress - VTEX - Vuejs - Laravel - Magento</p>
							</div>

							<div className="job">
								<h2>Grupo THX</h2>
								<h3>Webdesigner</h3>
								<h4>2014-2015</h4>
								<p>Responsible to create websites from zero (design to programming)  Teamwork in the development of some sites, creation of flyer, photographic books, business cards, banner, banners, etc.</p>
							</div>


							<div className="job last">
								<h2>My Connect Midia</h2>
								<h3>Designer Gráfico</h3>
								<h4>2012-2014</h4>
								<p>Development of ELLITE Magazine, Teamwork in the development of some sites, creation of flyer, photographic books, business cards, banner, banners, etc.</p>
							</div>

						</div>
					</div>


					<div className="yui-gf last">
						<div className="yui-u first">
							<h2>Education</h2>
						</div>
						<div className="yui-u">
							<h2>Indiana University - Bloomington, Indiana</h2>
							<h3>Dual Major, Economics and English &mdash; <strong>4.0 GPA</strong> </h3>
						</div>
					</div>


				</div>
			</div>
		</div>

		<div id="ft">
			<p>Jonathan Doe &mdash; herbert.webdesigner@gmail.com&mdash; (313) - 867-5309</p>
		</div>
        </div>
        </main>
        <Footer />
        </div>
    )

}