import { useState } from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../layout/header'
import Footer from '../layout/footer'
import Button from 'react-bootstrap/Button';
import PortfolioDiv from '../components/portfolio';

export default function Home() {
  const { locale, locales, asPath } = useRouter();
  const [cat_portfolio, setCatPortfolio] = useState('website');
  const scroll2El = elID => {
    window.scrollTo({
      top: document.getElementById(elID).offsetTop - 10,
      behavior: 'smooth',
    });
  };

  const onBtnClick = (e) => {
    e.preventDefault();
    const goto = e.target.getAttribute('goto');
    setTimeout(() => {
      scroll2El(goto);
    }, 100);
  }



  return (
      <div>
      <Head>
        <title>Herbert web developer - Freelancer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      
      <main className="main">


        <section className="content">
            <div className="container">
              <div className="row d-flex col-content">
                <div className='col col-md-8 col-flex'>
                  <h1 className='titulo'>
                    {(locale === 'pt') ?(
                    'Oi! 👋 Eu sou o Herbert,'+
                    'UI/UX designer'+
                    'Front-end')
                    :(
                      'Hi! 👋 I am Herbert,'+
                      'UI/UX designer'+
                      'Front-end'
                    )}
                  </h1>
                  <Button className="learn-more">
                  <span className="circle" aria-hidden="true">
                    <span className="icon arrow"></span>
                  </span>
                  <span className="button-text" goto="work" onClick={onBtnClick}> 
                  {(locale === 'pt') ?('PROJETOS'):('SEE MY WORKS')}
                  </span>
                </Button>
                </div>

                <div className='col col-md-4'>
                  <Image src="/eu.png" width={286} height={358} alt="Herbert Amaro Santana" priority />
                </div>
              </div>
            </div>
        </section>
        <ul className="circles">
           <li></li>
           <li></li>
           <li></li>
           <li></li>
           <li></li>
           <li></li>
           <li></li>
           <li></li>
           <li></li>
           <li></li>
        </ul>
      </main>
      
        <PortfolioDiv categoria={cat_portfolio} />
      
      <Footer />
    </div>
  )
}
